---
title: "knit"
author: "ChunEn Chu"
date: "2021/12/4"
output: pdf_document
---
## Age and Education
```{r, results='asis', echo=FALSE, message= FALSE}
library(tidyverse)
library(foreign)
library(labelled)
library(haven)
library(readstata13)
library(pollster)
library(knitr)
library(kableExtra)
library(sjlabelled)
library(rlang)

dta = read_dta("AVA_PRRI_Wave 2_final_wtd_banners_v3.dta")
aa <- dta%>% colnames()%>%str_subset("^Q")
dta%>%
  select(-c(aa, weight)) -> dtatry
sav = read_sav("AVA_PRRI_Wave 2_final_wtd.sav")
sav%>%
  merge(dtatry, by = "Respid") -> test1
dta1 = read_dta("AVS 2021 with Banners V2_coded open ends.dta")
dta2 = read_dta("AVA_PRRI_Wave 4_banners v2.dta")
dta3 = read_dta("AVA_PRRI_Wave 4.dta")
dta4 = read_dta("AVS 2021_final 9-30-21.dta")
colnames(dta1)[2] <- "weight"
merge(dta1,dta4, by = "Respid")-> t1
merge(dta2,dta3[-6], by = "Respid")-> t2
rename(t1, "race_m" = "racecat",
       "educ_m2" = "educat2",
       "region_m" = "region",
       "allcat_m" = "allcat",
       "reltrad_w4" = "reltrad2",
       "party_m" = "partycat",
       "ideo_m" = "ideocat")->t1
age_crosstab1 <- function(x) {
  x %>%
  select(age)%>%
  transmute(group1 = ifelse(age %in% 18:29, "B",
         ifelse(age %in% 30:49, "C", ifelse(age %in% 50:64, 
                                            "D", ifelse(age %in% 65:150, "E", "skip"))))) ->t1
x <- cbind(x, as.vector(t1))
values <- c("High school or Less", "High school or Less", "Some College",
            "College Graduate", "Post-Graduate", "skip")
x$Education <- values[x$educ]
x%>%
  mutate(edu_group1 = recode(Education, "High school or Less" = "F",
                               "Some College" = "G",
                               "College Graduate" = "H",
                               "Post-Graduate" = "I")) ->x
for (i in str_subset(colnames(x),"^Q")[1:5]) {
  crosstab(df = x, x= !!sym(i), y = group1, weight = weight,pct_type = "column") ->t1
  crosstab(df = x, x= !!sym(i), y= edu_group1, weight = weight, pct_type = "column") ->t2
merge(t1, t2, key = t1[1])-> t3
All_Americans_A <- apply(t3%>%select(-i),1,sum)/8

All_Americans_A[1] <- All_Americans_A[1]*4

t4 <- cbind(All_Americans_A,t3)
t4[t4 =="n"] <- "Unweighted sample size"
#t4%>%
#  as_tibble()-> t4
#t4 <- t4[c(6,2,3,4,5,1),]
t4%>%
  relocate(All_Americans_A, .after = i)%>%
  kable(caption =get_label(x[i]), digits = 0, 
        col.names = c(" ", "All_Americans\nA", '18-30\nB', '30-49\nC', '50-64\nD', '65+\nE',
                      'HighSchool or Less\nF', 'Some College\nG', 'College  Gradute\nH',
                      'Post-Gradute\nI')) %>%
  kable_styling("striped", full_width = T,
                position = "left", font_size = 8) %>%
  add_header_above(c(" " = 1, "All Americans" = 1, "Age groups" = 4, "Education" = 4))%>%
  print()
}
}
age_crosstab1(t2)
age_crosstab1(t1)
```


## Race, Region 

```{r, results='asis', echo=FALSE}
race_table <- function(x){
  for (i in str_subset(colnames(x),"^Q")[1:5]){
r1 <- crosstab(df= x, x = !!sym(i), y = race_m, weight = weight, pct_type = "column")
r2 <- crosstab(df= x, x = !!sym(i), y= educ_m2, weight = weight, pct_type = "column")
r3 <- crosstab(df= x, x = !!sym(i), y= region_m, weight = weight, pct_type = "column")
r4 <- crosstab(df = x, x = !!sym(i), y = allcat_m, weight =weight, pct_type = "column" )%>%select("All Americans")%>%
  rename("american" = "All Americans")
x%>%
  group_by(race_m)%>%
  count()%>%
  table()%>%
  colnames()%>%
  as.numeric()%>%
  rev()->size1

x%>%
  filter(race_m == 1)%>%
  group_by(educ_m2)%>%
  count()%>%
  table()%>%
  colnames()%>%
  as.numeric()%>%
  rev()->size2
x%>%
  group_by(region_m)%>%
  count()%>%
  table()%>%
  colnames()%>%
  as.numeric()%>%rev() -> size3
a <- c(1,size1)
b <-  c(1,size2)
c <-  c(1,size3)
r1%>%
  filter(!!sym(i) != "n") %>%
  rbind(a) ->r1
r2 %>%
  filter(!!sym(i) != "n")%>%
  rbind(b)%>%
  select(-i)->r2
r3%>%
  filter(!!sym(i) != "n")%>%
  rbind(c)%>%
  select(-i) ->r3
r5 <- cbind(r1,r2,r3,r4)
r5[r5 == 1] <- "Unweighted sample size"
r5%>%
  relocate(american, .after = i)%>%
  kable(caption =get_label(x[i]), digits = 0, 
        col.names = c(" ", "All_Americans\nA", 'White\nB', 'Black\nC', 'Hispanic\nD', 'Other\nE',
                      'Multiracial\nF', 'White, no 4-year college degree\nG', 'White, 4- year college degree +\nH',
                      'NorthEast\nI', 'MidWest\nJ', 'South\nK','West\nL')) %>%
  kable_styling("striped", full_width = T,
                position = "left", font_size = 8) %>%
  add_header_above(c(" " = 1, "All Americans" = 1, "Race/Ethnicity" = 5, "White education" = 2, "Region" = 4))-> r5
print(r5)
  }
}
race_table(t1)
race_table(t2)
```

