---
title: "politics"
author: "ChunEn Chu"
date: "2021/11/4"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(foreign)
library(labelled)
library(haven)
library(readstata13)
library(pollster)
library(knitr)
library(kableExtra)
library(sjlabelled)
library(rlang)
```

```{r}
dta = read_dta("AVA_PRRI_Wave 2_final_wtd_banners_v3.dta")
aa <- dta%>% colnames()%>%str_subset("^Q")
dta%>%
  select(-c(aa, weight)) -> dta1
sav = read_sav("AVA_PRRI_Wave 2_final_wtd.sav")
sav%>%
  merge(dta1, by = "Respid") -> test1
```

```{r}
r1 <- crosstab(df= test1, x = Q2_1, y = party_m, weight = weight, pct_type = "column")
r1 <- r1[,1:4]
r2 <- crosstab(df = test1, x = Q2_1, y = republican_news, weight = weight, pct_type = "column")
r2 <- r2[,1:5]
r3 <- crosstab(df = test1, x = Q2_1, y = ideo_m, weight = weight, pct_type = "column")
r3 <- r3[,1:4]
r4 <- crosstab(df = test1, x = Q2_1, y = allcat_m, weight =weight, pct_type = "column" )%>%select(-Q2_1)%>%
  rename("american" = "All Americans")
```

```{r}
test1%>%
  group_by(party_m)%>%
  count()%>%
  table()%>%
  colnames()%>%
  as.numeric()%>%
  rev()->size1

test1%>%
  group_by(republican_news)%>%
  count()%>%
  table()%>%
  colnames()%>%
  as.numeric()%>%
  rev()->size2
test1%>%
  group_by(ideo_m)%>%
  count()%>%
  table()%>%
  colnames()%>%
  as.numeric()%>%rev() -> size3

a <- c(1,size1)
b <-  c(1,size2)
c <-  c(1,size3)
r1%>%
  filter(Q2_1 != "n") %>%
  rbind(a) ->r1
r2 %>%
  filter(Q2_1 != "n")%>%
  rbind(b)%>%
  select(-Q2_1)->r2
r3%>%
  filter(Q2_1 != "n")%>%
  rbind(c)%>%
  select(-Q2_1) ->r3
```

```{r}
r5 <- cbind(r1,r2,r3,r4)
r5[r5 == 1] <- "Unweighted sample size"
r5%>%
  relocate(american, .after = Q2_1)%>%
  kable(caption =attr(test1$Q2_1, "label"), digits = 0, 
        col.names = c(" ", "All_Americans\nA", 'Republican\nB', 'Independent\nC', 'Democrat\nD', 'Fox News Republican\nE',
                      'Conservative TV (OANN, NewsMax) Republican\nF', 'No TV news Republican\nG', 'Mainstream news Republican\nH',
                      'Conservative\nI', 'Moderate\nJ', 'Liberal\nK')) %>%
  kable_styling("striped", full_width = F,
                position = "left", font_size = 12) %>%
  add_header_above(c(" " = 1, "All Americans" = 1, "Party Affiliation, in survey" = 3, "Republicans (only) by trusted TV news sourc" = 4, "Political Ideolog" = 3))
```

```{r}
politics_table <- function(x){
  for (i in str_subset(colnames(x),"^Q")[5:7]){
r1 <- crosstab(df= x, x = !!sym(i), y = party_m, weight = weight, pct_type = "column")
r1 <- r1[,1:4]
r2 <- crosstab(df = x, x = !!sym(i), y = republican_news, weight = weight, pct_type = "column")
r2 <- r2[,1:5]
r3 <- crosstab(df = x, x = !!sym(i), y = ideo_m, weight = weight, pct_type = "column")
r3 <- r3[,1:4]
r4 <- crosstab(df = x, x = !!sym(i), y = allcat_m, weight =weight, pct_type = "column" )%>%select(-i)%>%
  rename("american" = "All Americans")
x%>%
  group_by(party_m)%>%
  count()%>%
  table()%>%
  colnames()%>%
  as.numeric()%>%
  rev()->size1

x%>%
  group_by(republican_news)%>%
  count()%>%
  table()%>%
  colnames()%>%
  as.numeric()%>%
  rev()->size2
x%>%
  group_by(ideo_m)%>%
  count()%>%
  table()%>%
  colnames()%>%
  as.numeric()%>%rev() -> size3

a <- c(1,size1)
b <-  c(1,size2)
c <-  c(1,size3)
r1%>%
  filter(!!sym(i) != "n") %>%
  rbind(a) ->r1
r2 %>%
  filter(!!sym(i) != "n")%>%
  rbind(b)%>%
  select(-i)->r2
r3%>%
  filter(!!sym(i) != "n")%>%
  rbind(c)%>%
  select(-i) ->r3
r5 <- cbind(r1,r2,r3,r4)
r5[r5 == 1] <- "Unweighted sample size"
r5%>%
  relocate(american, .after = i)%>%
  kable(caption =attr(i, "label"), digits = 0, 
        col.names =  c(" ", "All_Americans\nA", 'Republican\nB', 'Independent\nC', 'Democrat\nD', 'Fox News Republican\nE',
                      'Conservative TV (OANN, NewsMax) Republican\nF', 'No TV news Republican\nG', 'Mainstream news Republican\nH',
                      'Conservative\nI', 'Moderate\nJ', 'Liberal\nK')) %>%
  kable_styling("striped", full_width = F,
                position = "left", font_size = 12) %>%
  add_header_above(c(" " = 1, "All Americans" = 1, "Party Affiliation, in survey" = 3, "Republicans (only) by trusted TV news sourc" = 4, "Political Ideolog" = 3))-> r5
print(r5)
  }
}
politics_table(test1)
```

