---
title: "Religion"
author: "ChunEn Chu"
date: "2021/11/14"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(foreign)
library(labelled)
library(haven)
library(readstata13)
library(pollster)
library(knitr)
library(kableExtra)
library(sjlabelled)
library(rlang)
```


```{r}
dta = read_dta("AVA_PRRI_Wave 2_final_wtd_banners_v3.dta")
aa <- dta%>% colnames()%>%str_subset("^Q")
dta%>%
  select(-c(aa, weight)) -> dta1
sav = read_sav("AVA_PRRI_Wave 2_final_wtd.sav")
sav%>%
  merge(dta1, by = "Respid") -> test1
```

```{r}
get_label(dta)%>%
  str_subset("Rel|rel|REL")
crosstab(df = test1, x = Q2_1, y = reltrad_w2, weight = weight, pct_type = "column")
dta%>%
  select(reli1)%>%
  group_by(reli1)%>%
  count()
```

```{r}
r1 <- crosstab(df = test1, x = Q2_1, y = reltrad_w2, weight = weight, pct_type = "column")
r1 <- r1[1:13]
r2 <- crosstab(df = test1, x = Q2_1, y = allcat_m, weight =weight, pct_type = "column" )%>%select(-Q2_1)%>%
  rename("american" = "All Americans")
```

```{r}
test1$reltrad_w2
test1%>%
  group_by(reltrad_w2)%>%
  count()%>%
  data.frame()%>%
  select(n) ->size1
size1 <- size1[-13,]
a <- c(1,size1)

r1%>%
  filter(Q2_1 != "n") %>%
  rbind(a) ->r1
r5 <- cbind(r1,r2)
r5[r5 == 1] <- "Unweighted sample size"
r5%>%
  relocate(american, .after = Q2_1)%>%
  kable(caption =attr(test1$Q2_1, "label"), digits = 0, 
        col.names =  c(" ", "All_Americans\nA", 'WhiteevangelicalProtestant\nB', 'WhitemainlineProtestant\nC', 'BlackProtestant\nD', 'HispanicProtestant\nE','OthernonwhiteProtestant\nF', 'WhiteCatholic\nG', 'HispanicCatholic\nH', 'Mormon
\nI', 'OtherChristian\nJ', 'Jewish\nK', 'Othernon-Christianreligion\nL','Unaffiliated\nM')) %>%
  kable_styling("striped", full_width = F,
                position = "left", font_size = 12) %>%
  add_header_above(c(" " = 1, "All Americans" = 1, "Religious Affiliation" = 12))-> r5
print(r5)
```



```{r, results='asis', echo=FALSE}
politics_table <- function(x){
  for (i in str_subset(colnames(x),"^Q")[5:7]){
r1 <- crosstab(df= x, x = !!sym(i), y = reltrad_w2, weight = weight, pct_type = "column")
r1 <- r1[,1:13]
r2 <- crosstab(df = x, x = !!sym(i), y = allcat_m, weight =weight, pct_type = "column" )%>%select(-i)%>%
  rename("american" = "All Americans")
test1%>%
  group_by(reltrad_w2)%>%
  count()%>%
  data.frame()%>%
  select(n) ->size1
size1 <- size1[-13,]
a <- c(1,size1)
r1%>%
  filter(!!sym(i) != "n") %>%
  rbind(a) ->r1

r5 <- cbind(r1,r2)
r5[r5 == 1] <- "Unweighted sample size"
r5%>%
  relocate(american, .after = i)%>%
  kable(caption =attr(i, "label"), digits = 0, 
        col.names =  c(" ", "All_Americans\nA", 'WhiteevangelicalProtestant\nB', 'WhitemainlineProtestant\nC', 'BlackProtestant\nD', 'HispanicProtestant\nE','OthernonwhiteProtestant\nF', 'WhiteCatholic\nG', 'HispanicCatholic\nH', 'Mormon
\nI', 'OtherChristian\nJ', 'Jewish\nK', 'Othernon-Christianreligion\nL','Unaffiliated\nM')) %>%
  kable_styling("striped", full_width = F,
                position = "left", font_size = 12) %>%
  add_header_above(c(" " = 1, "All Americans" = 1, "Religious Affiliation" = 12))-> r5
print(r5)
  }
}
politics_table(test1)
```

