---
title: "test2"
author: "ChunEn Chu"
date: "2021/10/5"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(foreign)
library(labelled)
library(haven)
library(readstata13)
library(pollster)
library(knitr)
library(kableExtra)
library(sjlabelled)
library(rlang)
```

```{r}
dta = read_dta("AVA_PRRI_Wave 2_final_wtd_banners_v3.dta")
dta%>%
  select(Respid,age, educ) ->dta1
sav = read_sav("AVA_PRRI_Wave 2_final_wtd.sav")

sav%>%
  merge(dta1, by = "Respid") -> test1
```


```{r}
create_crosstab <- function(x) {
  x %>%
  select(age)%>%
  transmute(group = ifelse(age %in% 18:29, "B",
         ifelse(age %in% 30:49, "C", ifelse(age %in% 50:64, 
                                            "D", ifelse(age %in% 65:150, "E", "skip"))))) ->t1
x <- cbind(x, as.vector(t1))
values <- c("High school or Less", "High school or Less", "Some College",
            "College Graduate", "Post-Graduate", "skip")
x$Education <- values[x$educ]
x%>%
  mutate(edu_group = recode(Education, "High school or Less" = "F",
                               "Some College" = "G",
                               "College Graduate" = "H",
                               "Post-Graduate" = "I")) ->x
crosstab(df = x, x= Q2_1, y = group, weight = weight,pct_type = "column") ->t1

crosstab(df = x, x= Q2_1, y= edu_group, weight = weight, pct_type = "column") ->t2
merge(t1, t2, key = t1[1])-> t3
All_Americans_A <- apply(t3%>%select(-Q2_1),1,sum)/8

All_Americans_A[1] <- All_Americans_A[1]*4

t4 <- cbind(All_Americans_A,t3)
t4$Q2_1[1] <- "Unweighted sample size"
t4%>%
  relocate(All_Americans_A, .after = Q2_1)%>%
  #rename(" " = "Q2_1")%>%
  kable(caption =attr(x$Q2_1, 'label'), digits = 0, 
        col.names = c(" ", "All_Americans\nA", '18-30\nB', '30-49\nC', '50-64\nD', '65+\nE',
                      'HighSchool or Less\nF', 'Some College\nG', 'College  Gradute\nH',
                      'Post-Gradute\nI')) %>%
  kable_styling("striped", full_width = F,
                position = "left", font_size = 12) %>%
  add_header_above(c(" " = 1, "All Americans" = 1, "Age groups" = 4, "Education" = 4))
}
create_crosstab(test1)
```

```{r}
create_crosstab1 <- function(x) {
  x %>%
  select(age)%>%
  transmute(group = ifelse(age %in% 18:29, "B",
         ifelse(age %in% 30:49, "C", ifelse(age %in% 50:64, 
                                            "D", ifelse(age %in% 65:150, "E", "skip"))))) ->t1
x <- cbind(x, as.vector(t1))
values <- c("High school or Less", "High school or Less", "Some College",
            "College Graduate", "Post-Graduate", "skip")
x$Education <- values[x$educ]
x%>%
  mutate(edu_group = recode(Education, "High school or Less" = "F",
                               "Some College" = "G",
                               "College Graduate" = "H",
                               "Post-Graduate" = "I")) ->x

}
create_crosstab1(test1)

test1 %>%
  select(age)%>%
  transmute(group = ifelse(age %in% 18:29, "B",
         ifelse(age %in% 30:49, "C", ifelse(age %in% 50:64, 
                                            "D", ifelse(age %in% 65:150, "E", "skip"))))) ->t1
test1 <- cbind(test1, as.vector(t1))

 crosstab(df = test1, x= test1[6], y = group, weight = weight,pct_type = "column")
as_string(colnames(test1[6]))

crosstab(df = test1, x= as_string(test1[6]), y = group, weight = weight,pct_type = "column")
test1[6]
```


